(()=>{
'use strict';
const SB_URL='https://ylaofxjqwpximxhmyrnd.supabase.co';
const SB_KEY='sb_publishable_MLqLExLZ4k0XkohUe5J-vw_2-EmUPkT';
const FN_BASE=SB_URL+'/functions/v1';
const GT='America/Guatemala',OPEN_START=9*3600,TARGET_END=20*3600+30*60,OPEN_END=23*3600,TARGET_SECONDS=TARGET_END-OPEN_START;
const GUN_RATE=100,MACHINE_RATE=200,MACHINE_DAILY_TARGET=2300,DAILY_TARGET=4600,MACHINE_PER_MIN=MACHINE_RATE/60,MACHINE_PER_SEC=MACHINE_RATE/3600;
const SERIAL={1:'SK984681DMX',2:'SK984682DMX'};
let supabase,authGranted=false,mode='setup',factorId='',verifyMode='',voltage={1:432,2:439};
const $=s=>document.querySelector(s),set=(s,v)=>{const e=$(s);if(e)e.textContent=String(v)},money=n=>'Q'+Number(n).toLocaleString('es-GT',{minimumFractionDigits:2,maximumFractionDigits:2}),watts=n=>Math.max(0,Math.round(n)).toLocaleString('es-GT')+' W';
const hms=n=>{n=Math.max(0,Math.floor(n));return `${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor((n%3600)/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
const login=$('#loginView'),app=$('#app'),setupView=$('#setupView'),verifyView=$('#verifyView'),trustedView=$('#trustedView'),setupForm=$('#setupForm'),setupUser=$('#setupUser'),setupPass=$('#setupPass'),setupPass2=$('#setupPass2'),setupPhone=$('#setupPhone'),setupEnroll=$('#setupEnroll'),setupError=$('#setupError'),verifyError=$('#verifyError'),otpInput=$('#otpInput'),factorArea=$('#smsLink'),setupSubmit=setupForm.querySelector('button[type="submit"]'),verifyBtn=$('#verifyBtn'),secondaryOtpBtn=$('#showOtpBtn');
function showAuth(v){[setupView,verifyView,trustedView].forEach(x=>x.classList.remove('active'));v.classList.add('active')}
function normalizeUser(v){return String(v||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9._-]/g,'').toLowerCase()}
function emailFor(u){return normalizeUser(u)+'@blexxon.invalid'}
function normalizePhone(v){let s=String(v||'').trim();const digits=s.replace(/\D/g,'');if(!digits)return'';if(s.startsWith('+'))return'+'+digits;if(digits.length===8)return'+502'+digits;return'+'+digits}
function deviceLabel(){const u=navigator.userAgent||'';return /iPhone/i.test(u)?'iPhone · sesión segura':/iPad/i.test(u)?'iPad · sesión segura':/Android/i.test(u)?'Android · sesión segura':/Windows/i.test(u)?'Windows · sesión segura':/Mac/i.test(u)?'Mac · sesión segura':'Navegador · sesión segura'}
async function loadSupabase(){if(window.supabase?.createClient)return window.supabase;await new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=fail;document.head.appendChild(s)});return window.supabase}
async function statusRegistered(){try{const r=await fetch(FN_BASE+'/blexxon-auth-status',{headers:{apikey:SB_KEY}});return !!(await r.json()).registered}catch(_){return false}}
function support(){alert('RECUPERACIÓN DE ACCESO\n\nPor seguridad, la contraseña no se recupera automáticamente. Contacte a soporte BLEXXON para validar su identidad y restablecer el acceso.')}
function authErrorMessage(err){const m=String(err?.message||err||'');if(/invalid.*code|challenge|totp|factor|mfa/i.test(m))return 'No se pudo validar el código de Authenticator. Revise que sea el código actual de 6 dígitos e intente nuevamente.';return m||'No se pudo completar la verificación.'}
function setSetupMessage(text,ok=false){setupError.textContent=text;setupError.style.color=ok?'#8ff2bc':'#ff8d92'}
function validatePasswords(){if(mode!=='setup'){setupSubmit.disabled=false;return true}const a=setupPass.value,b=setupPass2.value;if(!b){setSetupMessage('');setupSubmit.disabled=false;return false}if(a!==b){setSetupMessage('Las contraseñas no son iguales.');setupSubmit.disabled=true;return false}setSetupMessage('Las contraseñas coinciden.',true);setupSubmit.disabled=false;return true}
setupPass.addEventListener('input',validatePasswords);setupPass2.addEventListener('input',validatePasswords);
function configureLoginMode(){mode='login';setupView.querySelector('h1').textContent='Acceso BLEXXON';setupView.querySelector('p').innerHTML='<b>Propietario registrado.</b><br>Ingrese el usuario elegido y su contraseña. Si este dispositivo mantiene una sesión AAL2 válida, no se volverá a solicitar el segundo factor.';setupPass2.closest('.label').style.display='none';setupPhone.closest('.label').style.display='none';setupEnroll.closest('.label').style.display='none';setupSubmit.textContent='Ingresar';setupSubmit.disabled=false;setSetupMessage('');if(!$('#forgotSupport')){const b=document.createElement('button');b.id='forgotSupport';b.type='button';b.className='secondary-btn';b.style.width='100%';b.style.marginTop='10px';b.textContent='¿Olvidó su contraseña? Contactar a soporte';b.onclick=support;setupForm.after(b)}}
function configureSetupMode(){mode='setup';setupView.querySelector('h1').textContent='Registro inicial';setupView.querySelector('p').innerHTML='<b>Configuración única del propietario.</b><br>El cliente elige su usuario y su contraseña. Debe repetir la contraseña; si ambas coinciden podrá continuar. El teléfono queda únicamente como dato de contacto: el segundo factor se hará con una aplicación Authenticator, sin SMS.';setupPass2.closest('.label').style.display='';setupPhone.closest('.label').style.display='';setupEnroll.closest('.label').style.display='';setupPhone.placeholder='Ej. 5555 5555 o +502 5555 5555';setupSubmit.textContent='Registrar y configurar Authenticator';validatePasswords()}
async function showTrusted(session){set('#deviceIdText','BX-'+session.user.id.slice(0,8).toUpperCase());set('#deviceLabelText',deviceLabel()+' · Authenticator verificado');showAuth(trustedView)}
function resetFactorArea(){factorArea.removeAttribute('href');factorArea.onclick=e=>e.preventDefault();factorArea.innerHTML='';factorArea.style.display='block';factorArea.style.textAlign='center';factorArea.style.textDecoration='none';factorArea.style.cursor='default';factorArea.style.padding='14px';factorArea.style.borderRadius='16px';const old=$('#totpManualActions');if(old)old.remove()}
function directTotpUri(secret){if(!secret)return'';const label=encodeURIComponent('BLEXXON XELA:Javier Ramirez');const issuer=encodeURIComponent('BLEXXON XELA');return `otpauth://totp/${label}?secret=${encodeURIComponent(secret)}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`}
function renderEnrollmentQr(qr,secret,uri){resetFactorArea();factorArea.style.background='#ffffff';factorArea.style.cursor=uri?'pointer':'default';if(uri){factorArea.href=uri;factorArea.onclick=null}const img=document.createElement('img');img.src=qr;img.alt='Código QR para Authenticator';img.style.width='220px';img.style.maxWidth='100%';img.style.height='auto';img.style.display='block';img.style.margin='0 auto';factorArea.appendChild(img);const openLabel=document.createElement('div');openLabel.textContent=uri?'Toque aquí para abrir directamente en Authenticator':'Escanee este QR con su aplicación Authenticator';openLabel.style.color='#06111f';openLabel.style.fontWeight='800';openLabel.style.fontSize='13px';openLabel.style.marginTop='10px';factorArea.appendChild(openLabel);
 const actions=document.createElement('div');actions.id='totpManualActions';actions.style.marginTop='12px';actions.style.padding='14px';actions.style.border='1px solid rgba(255,255,255,.12)';actions.style.borderRadius='16px';actions.style.background='rgba(255,255,255,.04)';actions.style.textAlign='left';const syncNote=document.createElement('div');syncNote.innerHTML='<b>Nombre dentro de Authenticator:</b> Javier Ramirez · BLEXXON XELA<br><span style="font-size:12px;color:#9bb2c4">Si Google Authenticator muestra una cuenta de Gmail en la parte superior, esa cuenta solo sirve para sincronizar Authenticator. No cambia el usuario ni la contraseña de BLEXXON.</span>';actions.appendChild(syncNote);const manual=document.createElement('div');manual.style.marginTop='12px';manual.innerHTML='<b>Configuración manual:</b><br><span style="font-size:12px;color:#9bb2c4">Authenticator → + → Introducir clave de configuración → Cuenta: <b>Javier Ramirez · BLEXXON XELA</b> → Tipo: <b>Basado en tiempo</b>.</span>';actions.appendChild(manual);const secretTitle=document.createElement('div');secretTitle.textContent='Clave de configuración';secretTitle.style.marginTop='12px';secretTitle.style.fontSize='12px';secretTitle.style.color='#9bb2c4';actions.appendChild(secretTitle);const secretBox=document.createElement('div');secretBox.textContent=secret||'';secretBox.style.marginTop='5px';secretBox.style.padding='10px';secretBox.style.borderRadius='10px';secretBox.style.background='#06111f';secretBox.style.color='#f4f8ff';secretBox.style.fontWeight='800';secretBox.style.letterSpacing='1px';secretBox.style.wordBreak='break-all';actions.appendChild(secretBox);const copy=document.createElement('button');copy.type='button';copy.className='secondary-btn';copy.style.width='100%';copy.style.marginTop='10px';copy.textContent='Copiar clave manual';copy.onclick=async()=>{try{await navigator.clipboard.writeText(secret);copy.textContent='Clave copiada';setTimeout(()=>copy.textContent='Copiar clave manual',1800)}catch(_){prompt('Copie esta clave y péguela en Authenticator:',secret)}};actions.appendChild(copy);factorArea.insertAdjacentElement('afterend',actions)}
function renderAuthenticatorChallenge(){resetFactorArea();factorArea.style.background='rgba(255,255,255,.04)';factorArea.style.color='#d8e8f4';factorArea.innerHTML='<b>Abra su aplicación Authenticator</b><br><span style="font-size:12px">Use el código actual de 6 dígitos asociado a Javier Ramirez · BLEXXON XELA.</span>'}
async function enrollTotpFactor(){verifyError.textContent='';const fs=await supabase.auth.mfa.listFactors();if(fs.error)throw fs.error;for(const f of (fs.data.totp||[]).filter(x=>x.status!=='verified')){try{await supabase.auth.mfa.unenroll({factorId:f.id})}catch(_){}}
 const en=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'Javier Ramirez · BLEXXON XELA · M01-M02'});if(en.error)throw en.error;factorId=en.data.id;verifyMode='enroll';const secret=en.data.totp?.secret||'';const uri=directTotpUri(secret)||en.data.totp?.uri||'';verifyView.querySelector('h1').textContent='Configurar Authenticator';verifyView.querySelector('p').textContent='Puede tocar el QR para abrir Authenticator directamente, escanearlo desde otro dispositivo o copiar la clave manual. Después escriba el código de 6 dígitos generado por la aplicación.';renderEnrollmentQr(en.data.totp?.qr_code||'',secret,uri);otpInput.value='';otpInput.placeholder='000000';verifyBtn.textContent='Activar Authenticator';secondaryOtpBtn.style.display='';secondaryOtpBtn.textContent='Generar nuevo QR';showAuth(verifyView);setTimeout(()=>otpInput.focus(),200)}
async function challengeTotpFactor(f){verifyError.textContent='';factorId=f.id;verifyMode='challenge';verifyView.querySelector('h1').textContent='Verificación con Authenticator';verifyView.querySelector('p').textContent='Ingrese el código actual de 6 dígitos que aparece en su aplicación Authenticator para Javier Ramirez · BLEXXON XELA.';renderAuthenticatorChallenge();otpInput.value='';otpInput.placeholder='000000';verifyBtn.textContent='Verificar e ingresar';secondaryOtpBtn.style.display='none';showAuth(verifyView);setTimeout(()=>otpInput.focus(),200)}
async function routeSession(session){if(!session){configureLoginMode();showAuth(setupView);return}const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error)throw aal.error;if(aal.data.currentLevel==='aal2'){await showTrusted(session);return}const fs=await supabase.auth.mfa.listFactors();if(fs.error)throw fs.error;const verified=(fs.data.totp||[]).find(x=>x.status==='verified');if(verified){await challengeTotpFactor(verified);return}await enrollTotpFactor()}
async function bootAuth(){const {data:{session}}=await supabase.auth.getSession();if(session){await routeSession(session);return}const reg=await statusRegistered();reg?configureLoginMode():configureSetupMode();showAuth(setupView)}
setupForm.addEventListener('submit',async e=>{e.preventDefault();setSetupMessage('');const u=setupUser.value.trim(),p=setupPass.value,phone=normalizePhone(setupPhone.value),activationCode=setupEnroll.value.trim();try{
 if(mode==='setup'){
   if(!u){setSetupMessage('El cliente debe elegir un usuario.');return}if(p.length<8){setSetupMessage('La clave debe tener al menos 8 caracteres.');return}if(!validatePasswords())return;if(!phone){setSetupMessage('Ingrese un número de teléfono de contacto.');return}
   const r=await fetch(FN_BASE+'/blexxon-bootstrap-owner',{method:'POST',headers:{'Content-Type':'application/json',apikey:SB_KEY},body:JSON.stringify({username:u,password:p,phone,activationCode})});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo registrar');
   const loginRes=await supabase.auth.signInWithPassword({email:j.email,password:p});if(loginRes.error)throw loginRes.error;
   await enrollTotpFactor();
 }else{
   const si=await supabase.auth.signInWithPassword({email:emailFor(u),password:p});if(si.error)throw si.error;
   await routeSession(si.data.session);
 }
}catch(err){setSetupMessage(authErrorMessage(err))}});
secondaryOtpBtn.textContent='Generar nuevo QR';
secondaryOtpBtn.addEventListener('click',async()=>{if(verifyMode!=='enroll')return;try{if(factorId){try{await supabase.auth.mfa.unenroll({factorId})}catch(_){}}await enrollTotpFactor();verifyError.textContent='Se generó una nueva configuración de Authenticator.'}catch(e){verifyError.textContent=authErrorMessage(e)}});
verifyBtn.textContent='Verificar Authenticator';
verifyBtn.addEventListener('click',async()=>{verifyError.textContent='';try{if(!factorId)throw new Error('No hay un factor Authenticator preparado.');const code=otpInput.value.trim().replace(/\s/g,'');if(!/^\d{6}$/.test(code))throw new Error('Ingrese el código actual de 6 dígitos de Authenticator.');const ch=await supabase.auth.mfa.challenge({factorId});if(ch.error)throw ch.error;const vr=await supabase.auth.mfa.verify({factorId,challengeId:ch.data.id,code});if(vr.error)throw vr.error;authGranted=true;openPanel()}catch(e){verifyError.textContent=authErrorMessage(e)}});
$('#trustedLoginBtn').addEventListener('click',async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){location.reload();return}const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error||aal.data.currentLevel!=='aal2'){await routeSession(session);return}authGranted=true;openPanel()});
$('#resetDeviceBtn').addEventListener('click',async()=>{if(confirm('¿Cerrar la sesión segura de este dispositivo? En el próximo acceso se pedirá contraseña y código de Authenticator.')){await supabase.auth.signOut();location.reload()}});
function parts(d=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:GT,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d);return Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]))}
function stamp(d=new Date()){const p=parts(d);return `${String(p.day).padStart(2,'0')}/${String(p.month).padStart(2,'0')}/${p.year} ${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')}:${String(p.second).padStart(2,'0')}`}
function state(d=new Date()){const p=parts(d),sod=p.hour*3600+p.minute*60+p.second,withinHours=sod>=OPEN_START&&sod<OPEN_END,producing=sod>=OPEN_START&&sod<TARGET_END,targetReached=sod>=TARGET_END&&sod<OPEN_END,elapsedToTarget=Math.max(0,Math.min(TARGET_SECONDS,sod-OPEN_START)),remainingToTarget=Math.max(0,TARGET_SECONDS-elapsedToTarget),progress=100*elapsedToTarget/TARGET_SECONDS;return{p,sod,withinHours,producing,targetReached,elapsedToTarget,remainingToTarget,progress}}
const generatedPerMachine=e=>Math.min(MACHINE_DAILY_TARGET,MACHINE_RATE*(e/3600));
function updateVoltages(){const step=Math.floor(Date.now()/3000);for(const m of[1,2]){const base=m===1?432.5:439.5,wave=Math.sin((step+m*2)*.78)*6.8+Math.cos((step+m*5)*.31)*2.9;voltage[m]=Math.max(m===1?420:426,Math.min(m===1?444:451,base+wave))}}
function powerFor(m,st){if(!st.withinHours)return 0;if(st.targetReached)return m===1?6900:7200;const base=m===1?112500:118800,step=Math.floor(Date.now()/3000);return base+Math.sin((step+m)*.51)*6200+Math.cos((step+m*3)*.26)*3100}
function batteryFor(m,st){if(st.sod<OPEN_START)return m===1?98:97.5;const ratio=Math.max(0,Math.min(1,st.elapsedToTarget/TARGET_SECONDS)),start=m===1?98:97.5,drop=m===1?56:53,wiggle=Math.sin(Math.floor(Date.now()/3000)*(m===1?.22:.19))*.35;return Math.max(m===1?41.5:43.5,start-drop*ratio+wiggle)}
function update(){if(!authGranted||app.classList.contains('view-hidden')||app.style.display==='none')return;const st=state(),perToday=generatedPerMachine(st.elapsedToTarget),totalToday=perToday*2,currentMachine=st.producing?MACHINE_RATE:0,currentTotal=currentMachine*2,p1=powerFor(1,st),p2=powerFor(2,st),avg=(voltage[1]+voltage[2])/2,phase=!st.withinHours?'JORNADA FINALIZADA':st.producing?'PRODUCCIÓN ACTIVA · META Q2,300/MÁQUINA':'META DIARIA ALCANZADA · MONITOREO';set('#clock',`${String(st.p.hour).padStart(2,'0')}:${String(st.p.minute).padStart(2,'0')}:${String(st.p.second).padStart(2,'0')} · Guatemala`);set('#operation',!st.withinHours?'JORNADA FINALIZADA · 09:00–23:00':st.producing?'OPERANDO · Q200/h POR MÁQUINA':'META ALCANZADA · Q4,600');set('#kpiState',phase);set('#kpiNow',money(currentTotal)+'/h');set('#kpiToday',money(totalToday));set('#kpiPower',watts(p1+p2));set('#kpiVoltage',avg.toFixed(1)+' V');set('#passed',hms(st.elapsedToTarget));set('#remaining',hms(st.remainingToTarget));const cs=$('#cycleState'),cb=$('#cycleBar');if(cs)cs.textContent=phase;if(cb)cb.style.width=st.progress.toFixed(2)+'%';for(const m of[1,2]){const power=m===1?p1:p2,pct=batteryFor(m,st);set(`[data-voltage="${m}"]`,voltage[m].toFixed(1)+' V · dinámico · act. 3 s');set(`[data-power="${m}"]`,watts(power));set(`[data-hour="${m}"]`,money(currentMachine)+'/h');set(`[data-gun-a="${m}"]`,money(st.producing?GUN_RATE:0)+'/h');set(`[data-gun-b="${m}"]`,money(st.producing?GUN_RATE:0)+'/h');set(`[data-capacity="${m}"]`,money(st.producing?MACHINE_RATE:0)+'/h');set(`[data-today="${m}"]`,money(perToday));set(`[data-phase="${m}"]`,phase);const status=$(`[data-status="${m}"]`);if(status)status.textContent=!st.withinHours?'JORNADA FINALIZADA':st.producing?'2 / 2 PISTOLAS · PRODUCCIÓN ACTIVA':'META Q2,300 ALCANZADA';set(`[data-bat-pct="${m}"]`,pct.toFixed(1)+'%');set(`[data-bat-load="${m}"]`,st.withinHours?'Consumo asignado: '+watts(power):'Consumo asignado: 0 W');set(`[data-bat-status="${m}"]`,!st.withinHours?'Protegida · jornada finalizada':st.producing?`Descarga media-rápida · suministro M0${m}`:`Meta alcanzada · reserva estabilizada M0${m}`);const bar=$(`[data-bat-bar="${m}"]`);if(bar)bar.style.width=pct.toFixed(1)+'%'}set('#reportTime',stamp());set('#reportNow',money(currentTotal)+'/h');set('#reportToday',money(totalToday));set('#reportPhase',phase)}
function openPanel(){login.classList.add('view-hidden');login.style.display='none';app.classList.remove('view-hidden');app.style.display='block';updateVoltages();update();window.scrollTo(0,0)}
$('#logout').addEventListener('click',async()=>{authGranted=false;app.classList.add('view-hidden');app.style.display='none';login.classList.remove('view-hidden');login.style.display='grid';const {data:{session}}=await supabase.auth.getSession();session?showTrusted(session):bootAuth()});
$('#excel').addEventListener('click',()=>{const st=state(),per=generatedPerMachine(st.elapsedToTarget),rows=[['Maquina','Serie','Q/h','Q/min','Q/seg','Generado hoy','Meta diaria','Voltaje'],['M01',SERIAL[1],MACHINE_RATE,MACHINE_PER_MIN.toFixed(4),MACHINE_PER_SEC.toFixed(5),per.toFixed(2),MACHINE_DAILY_TARGET,voltage[1].toFixed(1)],['M02',SERIAL[2],MACHINE_RATE,MACHINE_PER_MIN.toFixed(4),MACHINE_PER_SEC.toFixed(5),per.toFixed(2),MACHINE_DAILY_TARGET,voltage[2].toFixed(1)]];const csv=rows.map(r=>r.join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Reporte_Xela_Javier.csv';a.click()});
setInterval(updateVoltages,3000);setInterval(update,1000);
(async()=>{try{const lib=await loadSupabase();supabase=lib.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await bootAuth()}catch(e){setSetupMessage('No se pudo iniciar la seguridad del portal. Contacte a soporte BLEXXON.')}})();
})();