(()=>{
'use strict';
const SB_URL='https://ylaofxjqwpximxhmyrnd.supabase.co';
const SB_KEY='sb_publishable_MLqLExLZ4k0XkohUe5J-vw_2-EmUPkT';
const FN_BASE=SB_URL+'/functions/v1';
const GT='America/Guatemala',OPEN_START=9*3600,TARGET_END=20*3600+30*60,OPEN_END=23*3600,TARGET_SECONDS=TARGET_END-OPEN_START;
const GUN_RATE=100,MACHINE_RATE=200,MACHINE_DAILY_TARGET=2300,DAILY_TARGET=4600,MACHINE_PER_MIN=MACHINE_RATE/60,MACHINE_PER_SEC=MACHINE_RATE/3600;
const SERIAL={1:'SK984681DMX',2:'SK984682DMX'};
let supabase,authGranted=false,mode='setup',factorId='',factorSecret='',voltage={1:432,2:439};
const $=s=>document.querySelector(s),set=(s,v)=>{const e=$(s);if(e)e.textContent=String(v)},money=n=>'Q'+Number(n).toLocaleString('es-GT',{minimumFractionDigits:2,maximumFractionDigits:2}),watts=n=>Math.max(0,Math.round(n)).toLocaleString('es-GT')+' W';
const hms=n=>{n=Math.max(0,Math.floor(n));return `${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor((n%3600)/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
const login=$('#loginView'),app=$('#app'),setupView=$('#setupView'),verifyView=$('#verifyView'),trustedView=$('#trustedView'),setupForm=$('#setupForm'),setupUser=$('#setupUser'),setupPass=$('#setupPass'),setupPass2=$('#setupPass2'),setupPhone=$('#setupPhone'),setupEnroll=$('#setupEnroll'),setupError=$('#setupError'),verifyError=$('#verifyError'),otpInput=$('#otpInput'),smsLink=$('#smsLink');
function showAuth(v){[setupView,verifyView,trustedView].forEach(x=>x.classList.remove('active'));v.classList.add('active')}
function normalizeUser(v){return String(v||'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9._-]/g,'').toLowerCase()}
function emailFor(u){return normalizeUser(u)+'@blexxon.invalid'}
function deviceLabel(){const u=navigator.userAgent||'';return /iPhone/i.test(u)?'iPhone · sesión segura':/iPad/i.test(u)?'iPad · sesión segura':/Android/i.test(u)?'Android · sesión segura':/Windows/i.test(u)?'Windows · sesión segura':/Mac/i.test(u)?'Mac · sesión segura':'Navegador · sesión segura'}
async function loadSupabase(){if(window.supabase?.createClient)return window.supabase;await new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=fail;document.head.appendChild(s)});return window.supabase}
async function statusRegistered(){try{const r=await fetch(FN_BASE+'/blexxon-auth-status',{headers:{apikey:SB_KEY}});return !!(await r.json()).registered}catch(_){return false}}
function support(){alert('RECUPERACIÓN DE ACCESO\n\nPor seguridad, la contraseña no se recupera automáticamente. Contacte a soporte BLEXXON para validar su identidad y restablecer el acceso.')}
function configureLoginMode(){mode='login';setupView.querySelector('h1').textContent='Acceso BLEXXON';setupView.querySelector('p').innerHTML='<b>Propietario registrado.</b><br>Ingrese usuario y contraseña. En este dispositivo, si la sesión segura sigue activa, no se volverá a pedir el segundo factor.';setupPass2.closest('.label').style.display='none';setupPhone.closest('.label').style.display='none';setupEnroll.closest('.label').style.display='none';setupForm.querySelector('button[type="submit"]').textContent='Ingresar';if(!$('#forgotSupport')){const b=document.createElement('button');b.id='forgotSupport';b.type='button';b.className='secondary-btn';b.style.width='100%';b.style.marginTop='10px';b.textContent='¿Olvidó su contraseña? Contactar a soporte';b.onclick=support;setupForm.after(b)}}
function configureSetupMode(){mode='setup';setupView.querySelector('h1').textContent='Registro inicial';setupPass2.closest('.label').style.display='';setupPhone.closest('.label').style.display='';setupEnroll.closest('.label').style.display='';setupForm.querySelector('button[type="submit"]').textContent='Continuar a verificación'}
async function showTrusted(session){set('#deviceIdText','BX-'+session.user.id.slice(0,8).toUpperCase());set('#deviceLabelText',deviceLabel());showAuth(trustedView)}
async function bootAuth(){const {data:{session}}=await supabase.auth.getSession();if(session){await showTrusted(session);return}const reg=await statusRegistered();reg?configureLoginMode():configureSetupMode();showAuth(setupView)}
setupForm.addEventListener('submit',async e=>{e.preventDefault();setupError.textContent='';const u=setupUser.value.trim(),p=setupPass.value,phone=setupPhone.value.trim(),activationCode=setupEnroll.value.trim();try{
 if(mode==='setup'){
   if(p.length<8){setupError.textContent='La clave debe tener al menos 8 caracteres.';return}if(p!==setupPass2.value){setupError.textContent='Las claves no coinciden.';return}
   const r=await fetch(FN_BASE+'/blexxon-bootstrap-owner',{method:'POST',headers:{'Content-Type':'application/json',apikey:SB_KEY},body:JSON.stringify({username:u,password:p,phone,activationCode})});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo registrar');
   const loginRes=await supabase.auth.signInWithPassword({email:j.email,password:p});if(loginRes.error)throw loginRes.error;
   const en=await supabase.auth.mfa.enroll({factorType:'totp',friendlyName:'BLEXXON XELA propietario'});if(en.error)throw en.error;factorId=en.data.id;factorSecret=en.data.totp.secret;smsLink.href=en.data.totp.uri;smsLink.textContent='Abrir / configurar Authenticator';verifyView.querySelector('p').textContent='Configure Authenticator con este enlace o con la clave manual y escriba el código de 6 dígitos. Esta verificación se realiza una sola vez mientras la sesión segura de este dispositivo permanezca activa.';showAuth(verifyView);
 }else{
   const si=await supabase.auth.signInWithPassword({email:emailFor(u),password:p});if(si.error)throw si.error;
   const aal=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal.error)throw aal.error;
   if(aal.data.nextLevel==='aal2'&&aal.data.currentLevel!=='aal2'){const fs=await supabase.auth.mfa.listFactors();if(fs.error)throw fs.error;const f=fs.data.totp.find(x=>x.status==='verified')||fs.data.totp[0];if(!f)throw new Error('No se encontró el segundo factor. Contacte a soporte.');factorId=f.id;factorSecret='';smsLink.href='#';smsLink.textContent='Abra su aplicación Authenticator';verifyView.querySelector('p').textContent='Este acceso requiere el código de su Authenticator porque la sesión segura de este dispositivo ya no estaba disponible.';showAuth(verifyView)}else{await showTrusted(si.data.session)}
 }
}catch(err){setupError.textContent=err?.message||'Error de acceso'}});
$('#showOtpBtn').addEventListener('click',()=>{verifyError.textContent=factorSecret?'Clave manual Authenticator: '+factorSecret:'Use el código actual de su aplicación Authenticator.'});
$('#verifyBtn').addEventListener('click',async()=>{verifyError.textContent='';try{if(!factorId)throw new Error('No hay verificación pendiente.');const ch=await supabase.auth.mfa.challenge({factorId});if(ch.error)throw ch.error;const vr=await supabase.auth.mfa.verify({factorId,challengeId:ch.data.id,code:otpInput.value.trim()});if(vr.error)throw vr.error;authGranted=true;openPanel()}catch(e){verifyError.textContent=e?.message||'Código incorrecto'}});
$('#trustedLoginBtn').addEventListener('click',async()=>{const {data:{session}}=await supabase.auth.getSession();if(session){authGranted=true;openPanel()}else{location.reload()}});
$('#resetDeviceBtn').addEventListener('click',async()=>{if(confirm('¿Cerrar la sesión segura de este dispositivo? En el próximo acceso se pedirá contraseña y segundo factor.')){await supabase.auth.signOut();location.reload()}});
function parts(d=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:GT,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d);return Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]))}
function stamp(d=new Date()){const p=parts(d);return `${String(p.day).padStart(2,'0')}/${String(p.month).padStart(2,'0')}/${p.year} ${String(p.hour).padStart(2,'0')}:${String(p.minute).padStart(2,'0')}:${String(p.second).padStart(2,'0')}`}
function state(d=new Date()){const p=parts(d),sod=p.hour*3600+p.minute*60+p.second,withinHours=sod>=OPEN_START&&sod<OPEN_END,producing=sod>=OPEN_START&&sod<TARGET_END,targetReached=sod>=TARGET_END&&sod<OPEN_END,elapsedToTarget=Math.max(0,Math.min(TARGET_SECONDS,sod-OPEN_START)),remainingToTarget=Math.max(0,TARGET_SECONDS-elapsedToTarget),progress=100*elapsedToTarget/TARGET_SECONDS;return{p,sod,withinHours,producing,targetReached,elapsedToTarget,remainingToTarget,progress}}
const generatedPerMachine=e=>Math.min(MACHINE_DAILY_TARGET,MACHINE_RATE*(e/3600));
function updateVoltages(){const step=Math.floor(Date.now()/3000);for(const m of[1,2]){const base=m===1?432.5:439.5,wave=Math.sin((step+m*2)*.78)*6.8+Math.cos((step+m*5)*.31)*2.9;voltage[m]=Math.max(m===1?420:426,Math.min(m===1?444:451,base+wave))}}
function powerFor(m,st){if(!st.withinHours)return 0;if(st.targetReached)return m===1?6900:7200;const base=m===1?112500:118800,step=Math.floor(Date.now()/3000);return base+Math.sin((step+m)*.51)*6200+Math.cos((step+m*3)*.26)*3100}
function batteryFor(m,st){if(st.sod<OPEN_START)return m===1?98:97.5;const ratio=Math.max(0,Math.min(1,st.elapsedToTarget/TARGET_SECONDS)),start=m===1?98:97.5,drop=m===1?56:53,wiggle=Math.sin(Math.floor(Date.now()/3000)*(m===1?.22:.19))*.35;return Math.max(m===1?41.5:43.5,start-drop*ratio+wiggle)}
function update(){if(!authGranted||app.classList.contains('view-hidden')||app.style.display==='none')return;const st=state(),perToday=generatedPerMachine(st.elapsedToTarget),totalToday=perToday*2,currentMachine=st.producing?MACHINE_RATE:0,currentTotal=currentMachine*2,p1=powerFor(1,st),p2=powerFor(2,st),avg=(voltage[1]+voltage[2])/2,phase=!st.withinHours?'JORNADA FINALIZADA':st.producing?'PRODUCCIÓN ACTIVA · META Q2,300/MÁQUINA':'META DIARIA ALCANZADA · MONITOREO';set('#clock',`${String(st.p.hour).padStart(2,'0')}:${String(st.p.minute).padStart(2,'0')}:${String(st.p.second).padStart(2,'0')} · Guatemala`);set('#operation',!st.withinHours?'JORNADA FINALIZADA · 09:00–23:00':st.producing?'OPERANDO · Q200/h POR MÁQUINA':'META ALCANZADA · Q4,600');set('#kpiState',phase);set('#kpiNow',money(currentTotal)+'/h');set('#kpiToday',money(totalToday));set('#kpiPower',watts(p1+p2));set('#kpiVoltage',avg.toFixed(1)+' V');set('#passed',hms(st.elapsedToTarget));set('#remaining',hms(st.remainingToTarget));const cs=$('#cycleState'),cb=$('#cycleBar');if(cs)cs.textContent=phase;if(cb)cb.style.width=st.progress.toFixed(2)+'%';for(const m of[1,2]){const power=m===1?p1:p2,pct=batteryFor(m,st);set(`[data-voltage="${m}"]`,voltage[m].toFixed(1)+' V · dinámico · act. 3 s');set(`[data-power="${m}"]`,watts(power));set(`[data-hour="${m}"]`,money(currentMachine)+'/h');set(`[data-gun-a="${m}"]`,money(st.producing?GUN_RATE:0)+'/h');set(`[data-gun-b="${m}"]`,money(st.producing?GUN_RATE:0)+'/h');set(`[data-capacity="${m}"]`,money(st.producing?MACHINE_RATE:0)+'/h');set(`[data-today="${m}"]`,money(perToday));set(`[data-phase="${m}"]`,phase);const status=$(`[data-status="${m}"]`);if(status)status.textContent=!st.withinHours?'JORNADA FINALIZADA':st.producing?'2 / 2 PISTOLAS · PRODUCCIÓN ACTIVA':'META Q2,300 ALCANZADA';set(`[data-bat-pct="${m}"]`,pct.toFixed(1)+'%');set(`[data-bat-load="${m}"]`,st.withinHours?'Consumo asignado: '+watts(power):'Consumo asignado: 0 W');set(`[data-bat-status="${m}"]`,!st.withinHours?'Protegida · jornada finalizada':st.producing?`Descarga media-rápida · suministro M0${m}`:`Meta alcanzada · reserva estabilizada M0${m}`);const bar=$(`[data-bat-bar="${m}"]`);if(bar)bar.style.width=pct.toFixed(1)+'%'}set('#reportTime',stamp());set('#reportNow',money(currentTotal)+'/h');set('#reportToday',money(totalToday));set('#reportPhase',phase)}
function openPanel(){login.classList.add('view-hidden');login.style.display='none';app.classList.remove('view-hidden');app.style.display='block';updateVoltages();update();window.scrollTo(0,0)}
$('#logout').addEventListener('click',async()=>{authGranted=false;app.classList.add('view-hidden');app.style.display='none';login.classList.remove('view-hidden');login.style.display='grid';const {data:{session}}=await supabase.auth.getSession();session?showTrusted(session):bootAuth()});
$('#excel').addEventListener('click',()=>{const st=state(),per=generatedPerMachine(st.elapsedToTarget),rows=[['Maquina','Serie','Q/h','Q/min','Q/seg','Generado hoy','Meta diaria','Voltaje'],['M01',SERIAL[1],MACHINE_RATE,MACHINE_PER_MIN.toFixed(4),MACHINE_PER_SEC.toFixed(5),per.toFixed(2),MACHINE_DAILY_TARGET,voltage[1].toFixed(1)],['M02',SERIAL[2],MACHINE_RATE,MACHINE_PER_MIN.toFixed(4),MACHINE_PER_SEC.toFixed(5),per.toFixed(2),MACHINE_DAILY_TARGET,voltage[2].toFixed(1)]];const csv=rows.map(r=>r.join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='Reporte_Xela_Javier.csv';a.click()});
setInterval(updateVoltages,3000);setInterval(update,1000);
(async()=>{try{const lib=await loadSupabase();supabase=lib.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await bootAuth()}catch(e){setupError.textContent='No se pudo iniciar la seguridad del portal. Contacte a soporte BLEXXON.'}})();
})();